apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver
  labels:
    app: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
        - name: identityserver
          image: identityserver:latest
          imagePullPolicy: Never          # minikube içindeki yerel imajı kullan
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"     # uygulamanın 8080'de dinlemesini sağlar
          livenessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /.well-known/openid-configuration
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
