apiVersion: v1
kind: Service
metadata:
  name: identityserver-service
spec:
  selector:
    app: identityserver
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
